### PR TITLE
Upgrade httpsnoop v1.0.1 => v1.0.3

### LINKED ISSUE #234: [question] upgrade httpsnoop
**Describe the problem you're having**

I am using multiple dependencies, some using github.com/felixge/httpsnoop@v1.0.3.
Would it be possible to upgrade httpsnoop to 1.0.3? As far as I can tell, there are no breaking changes.
…

**Versions**
> Go version: go version go1.19 linux/amd64

> package version: 3e030244b4ba0480763356fc8ca0ade6222e2da0

…

**"Show me the code!"**

```shell-session
go work sync
go: version constraints conflict:
	github.com/honeycombio/beeline-go@v1.1.1 requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
	github.com/letsencrypt/boulder@v0.0.0-20220331220046-b23ab962616e requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
	github.com/sigstore/sigstore@v1.3.0 requires github.com/felixge/httpsnoop@v1.0.3, but github.com/felixge/httpsnoop@v1.0.1 is requested
```
…

**"Possible solution"**

Upgrade httpsnoop using `go get -u github.com/felixge/httpsnoop`.

### PR DESCRIPTION
**Pull request by malt3**
Fixes #234

**Summary of Changes**

1. Upgrade httpsnoop

### CODE REVIEW

**Comment by amustaque97** [comment]
Can you please fix the CI pipeline failure issue? I will also take a look if updating the `httpsnoop` version is a breaking change or not. 

Thank you

**Comment by malt3** [comment]
> Can you please fix the CI pipeline failure issue?

Here you go https://github.com/gorilla/handlers/pull/236

**Comment by amustaque97** [comment]
Hi @malt3, oops I should write it briefly. You need to fix the pipeline in the current PR. 
Here is the required diff to understand file changes better

```diff
diff --git a/handlers_go18_test.go b/handlers_go18_test.go
index d8e6321..ec227cc 100644
--- a/handlers_go18_test.go
+++ b/handlers_go18_test.go
@@ -1,3 +1,4 @@
+//go:build go1.8
 // +build go1.8
 
 package handlers
```

If you find it difficult to understand. Save the above diff output in a file let's say `patch.txt` and apply the patch `git apply patch.txt`. Add a commit message and push the changes. 

Indeed this is not a breaking change, we can request the actual maintainer to merge this PR.

**Comment by malt3** [comment]
It is very weird for me to resolve existing problems in this unrelated PR. I also question wether you are an actual maintainer of this project. Maintainers can edit the PR so feel free to apply the exact patch you proposed to me yourself.

**Comment by amustaque97** [comment]
> It is very weird for me to resolve existing problems in this unrelated PR.

I agree but keeping in mind that the original maintainer is quite busy and it's better to accommodate that minor change in the same PR. 


>  I also question whether you are an actual maintainer of this project. Maintainers can edit the PR so feel free to apply the exact patch you proposed to me yourself.

No, I'm not the actual maintainer that's why I'm requesting you. 🙂

**Comment by malt3** [comment]
I see. :smile: 

Sorry for making this complicated initially.

**Review by amustaque97 — APPROVED** [review]
Hi @elithrar please merge this PR.

Thank you

**Comment by coreydaley** [comment]
Completed via https://github.com/gorilla/handlers/pull/241

**Pull request closed without merging**
