### PR TITLE
Set Vary header when allowedOrigins is "*"

### PR DESCRIPTION
**Pull request by matiasanaya**
As per:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#CORS_and_caching

### CODE REVIEW

**Comment by elithrar** [comment]
Do you mean "when the Access-Control-Allow-Origin header is NOT "*" (any origin) then set the Vary header?"

> If the server *specifies an origin host rather than "*"*, then it must also include Origin in the Vary response header to indicate to clients that server responses will differ based on the value of the Origin request header.

**Comment by matiasanaya** [comment]
@elithrar by _when allowedOrigins is "*"_ I mean _when `handlers.cors.allowedOrigins == []string{"*"}`_

`Access-Control-Allow-Origin` header is never set to `*` by this library, but instead if the origin is allowed, it is echoes back in the `Access-Control-Allow-Origin` header, which is why the `Vary: Origin` header is required.

_"when the Access-Control-Allow-Origin header is NOT "*" (any origin) then set the Vary header"_ is not correct since the `Vary: Origin` header is not required if you are only allowing one origin (which is the current implementation)

Is the issue with this PR the commit message? I am happy to provide further examples and a more detailed explanation on why the current implementation is broken, if needed.

**Comment by elithrar** [comment]
Yes, please clarify the commit message. It should read “set the Vary header
when multiple origins are set in the ACAO header”

**Comment by matiasanaya** [comment]
@elithrar I've changed the commit message to the proposed one, though, as far as my understanding goes, multiple origins are never set in the ACAO header...

Additionally the issue here might be that the ACAO header is never set to `*` even if the configuration is set to allow `*`. Not sure if that's a decision made consciously, or a change inadvertently introduced. 

If the ACAO header should be set to `*` when the configuration allows `*` (instead of echoing the origin), then the `Vary` header is not required and this PR should be reverted.

**Comment by elithrar** [comment]
* Multiple origins are allowed - https://www.w3.org/TR/cors/#access-control-allow-origin-response-header - although some client implementations only accept one, so the server needs to return one based on whether the origin is in the list of accepted origins
* This library can return "*" if set, albeit "*" should only be set when you are aware of the security implications

**Comment by matiasanaya** [comment]
I believe I've done a poor job at communicating the issue at hand. I'll try again:

The test case named `"*_allowed"` fails, which means that intermediate caches will return incorrect (cached) responses to clients if more than one origin is being used, even though all of them should be allowed.

```
package handlerstest

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gorilla/handlers"
)

func TestCORS(t *testing.T) {
	table := []struct {
		name               string
		allowedOrigins     []string
		origin             string
		expectedACAOHeader string
		expectedVaryHeader string
	}{
		{
			name:               "*_allowed",
			allowedOrigins:     []string{"*"},
			origin:             "a-origin",
			expectedVaryHeader: "Origin",
			expectedACAOHeader: "a-origin",
		},
		{
			name:               "two_origins_allowed",
			allowedOrigins:     []string{"a-origin", "another-origin"},
			origin:             "a-origin",
			expectedVaryHeader: "Origin",
			expectedACAOHeader: "a-origin",
		},
	}
	for _, r := range table {
		t.Run(r.name, func(t *testing.T) {
			cors := handlers.CORS(handlers.AllowedOrigins(r.allowedOrigins))

			req, err := http.NewRequest("GET", "/", nil)
			req.Header.Add("Origin", r.origin)
			if err != nil {
				t.Fatal(err)
			}
			rr := httptest.NewRecorder()

			cors(http.HandlerFunc(h)).ServeHTTP(rr, req)

			acao := rr.Header().Get("Access-Control-Allow-Origin")
			vary := rr.Header().Get("Vary")

			if acao != r.expectedACAOHeader {
				t.Errorf(`unexpected Access-Control-Allow-Origin header: got "%v" want "%v"`, acao, r.expectedACAOHeader)
			}

			if vary != r.expectedVaryHeader {
				t.Errorf(`unexpected Vary header: got "%v" want "%v"`, vary, r.expectedVaryHeader)
			}
		})
	}
}

func h(http.ResponseWriter, *http.Request) {}
```

ps. @elithrar 

1) How do you configure the library to respond with `Access-Control-Allow-Origin: *`? (Assuming that's what you meant by -> _"" if set, albeit ""_)

2) I understand that "Multiple origins are allowed" _by the spec_, I meant that "multiple origins are never set in the ACAO header..." _by this library_

3) PR is labeled as `work-required`, have I missed anything?

**Comment by elithrar** [comment]
If you set `handlers.AllowedOrigins([]string{"*"})` - then the library will respond with `Access-Control-Allow-Origin: $REQUEST_ORIGIN`, where `$REQUEST_ORIGIN` is the content of the `Origin` header from the CORS OPTIONS request. That is to say, every origin is allowed.

The library also accepts a slice of origin names, but only returns the matching Origin in the ACAO response header if it is allowed, as some clients won't accept a comma-separated list of Origin values in the ACAO response header.

**Comment by matiasanaya** [comment]
Is there anything holding this change back?

**Comment by elithrar** [comment]
I’ll review tomorrow. Apologies for the slowness: busy few months!

**Comment by achansen121** [comment]
Shouldn't this also be set if `ch.allowedOriginValidator` is not `nil`?

**Comment by matiasanaya** [comment]
@elithrar have you given up on this PR? Is there anything I can do to help it move forward?

**Comment by elithrar** [comment]
I unfortunately haven’t had time to review this, and didn’t get confirmation that my points were addressed.

I’m open to someone else reviewing this PR and ensuring it addresses those points.

**Pull request closed without merging**
