### PR TITLE
http.Flusher and http.CloseNotifier interfaces in logging wrappers

### PR DESCRIPTION
**Pull request by sergeyt**
need http.Flusher and http.CloseNotifier to support `Server Sent Events`

### CODE REVIEW

**Comment by kisielk** [comment]
I'm not sure I like the solution of claiming to support interfaces which are not actually supported and then return an error or panicking if an attempt is made to use them. Usually if someone asserts a particular interface from a value they expect it to work...

**Comment by sergeyt** [comment]
@kisielk do you agree to use multiple wrappers for combinations of http.Hijacker, http.Flusher, http.CloseNotifier interfaces? if all three interfaces are supported (usual case) then use one common wrapper. BTW there is also io.ReaderFrom interface rarely used in http handlers.

**Comment by kisielk** [comment]
Yeah I think that's the only way to reasonably do this without effectively throwing away type safety :/

At least the implementation is private so we can always adjust it if someone comes up with a better solution.

We could probably put Flush() on all of the handlers and just no-op it if it's not supported by the underlying writer, the guarantees provided by it seem fairly loose based on the net/http documentation.

**Comment by sergeyt** [comment]
ok, I'll update the PR. Also please confirm that http.Flusher will be supported by default without panic, so need only 3 wrappers (Hijacker and CloseNotifier) for now, right?

**Comment by kisielk** [comment]
Yeah I think we can support Flusher by default. So we need one wrapper for Hijacker, one for CloseNotifier and then another wrapper which embeds them both (hijackingCloseNotifier ?) and one which has neither of those.

**Comment by sergeyt** [comment]
ok, let it be

**Comment by sergeyt** [comment]
@kisielk please see update

**Comment by kisielk** [comment]
I think that works, thanks.

**Comment by sergeyt** [comment]
@kisielk just checked this does not work, forgot to add http.Flusher to loggingResponseWriter

**Comment by kisielk** [comment]
Ah yeah, forgot that needs to be there :)

**Comment by sergeyt** [comment]
I'll create a PR with the fix.

**Pull request merged**
