### PR TITLE
Add URL scrubbing as an option with the logging handlers

### PR DESCRIPTION
**Pull request by Daniel-B-Smith**
There are cases where users may not wish to log part of a URL, e.g. when a part of the query string should be a secret. This change adds the ability to add a scrubbing function that will run on the URL before it is logged.

### CODE REVIEW

**Comment by kisielk** [comment]
This method will only work if `req.RequestURI` is blank. I think it's better to wrap the logging handler in another middleware that modifies the `req` itself before it is logged.

**Comment by Daniel-B-Smith** [comment]
Thanks. I missed that since the URL is copied before executing the next handler. As it stands, the semantics are a little weird where mutating the URL does nothing but mutating the RequestURI does have an effect. Making that consistent requires a more invasive change that I don't feel strongly about. I'm going to close this.

**Comment by Daniel-B-Smith** [comment]
It appears the issue I was having was because our version of handlers doesn't have f7731994851a8b00d742b6711dbe840ea982833e in it. Oops.

**Comment by kisielk** [comment]
I think once #130 gets turned into a PR and merged it will be easy to create custom log formatters, including scrubbing etc.

**Pull request closed without merging**
