### PR TITLE
RecoveryHandler should not handle http.ErrAbortHandler.

### PR DESCRIPTION
**Pull request by lunemec**
Based on discussion https://github.com/golang/go/issues/28239 .

### CODE REVIEW

**Comment by elithrar** [comment]
Can you expand more on the discussion?

Brad points out that you can’t capture the original cause, since the abort
could be anything. Thus it’s not clear why the PR is making an exception
for ErrAbortHandler.

**Comment by lunemec** [comment]
Sure. Based on the original discussion, as the error usually means that the handler execution was aborted, it makes no sense to log this error. There is no action to be taken on such error messages.

I started digging in this after seeing this in my logs and it triggering alert:
```
2019/06/05 05:05:21 http: superfluous response.WriteHeader call from github.com/GlobalWebIndex/gateway/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
PANIC RECOVERED: [net/http: abort Handler]
```
But there is simply nothing I can do. The Handler was aborted and as Brad stated its impossible to get to the underlying cause.

And as its stated in the docs:
```
ErrAbortHandler is a sentinel panic value to abort a handler. While any panic from ServeHTTP aborts the response to the client, panicking with ErrAbortHandler also suppresses logging of a stack trace to the server's error log.
```
It should suppress the logging of stack traces in the logs. So I think the panic handler should too.

**Comment by lunemec** [comment]
Oh and it should be only for Go >= 1.8, do you have some pattern for that already in use?

**Comment by elithrar** [comment]
I think it’s still useful to log it - when a client asks “my download keeps
failing” - etc.

Are you seeing a huge number of logs attributed to this?

**Comment by lunemec** [comment]
No, just 1 record. I'm still not sure if it makes sense to log this. I can't think of action I would take based on the lack of information that is logged.

**Comment by elithrar** [comment]
I'd like to leave it as-is. The library probably shouldn't be logging on
behalf of the user (libraries shouldn't log in general) but special-casing
this doesn't make a whole lot of sense.

You are welcome to implement your own RecoveryHandler instead.

**Pull request closed without merging**
