### PR TITLE
distinguish between explicit and implicit `*`

### LINKED ISSUE #117: breaking change with returned Access-Control-Allow-Origin header
Prior to https://github.com/gorilla/handlers/pull/116, specifying `AllowedOriginValidator` acted as an override to `AllowedOrigins`. Afterwards, the same configuration will return `Access-Control-Allow-Origin: *` because of the default value for `allowedOrigins`.

```
// before: will only reflect allowed origins
// after: will reflect "*"
gorilla.CORS(
  gorilla.AllowedOriginValidator(myValidator)
)
```

Fixing this requires specifying a blank `AllowedOrigins` to override the default value:

```
gorilla.CORS(
  gorilla.AllowedOrigins([]string{})
  gorilla.AllowedOriginValidator(myValidator)
)
```

### PR DESCRIPTION
**Pull request by cainlevy**
Fixes #117 by distinguishing between an explicit and implicit `AllowedOrigins([]string{"*"})`. This means that the origin will be reflected when a custom validator says it's okay and there is no contradictory `AllowedOrigins(...)` configuration.

If there is no custom validator, or the validator is paired with an explicit `*` (oops), then the allowed origin is a properly opaque `*` that will disable credentials.

Scrutiny and ideas for alternate implementations are welcome! 😓

### CODE REVIEW

**Comment by elithrar** [comment]
Thanks @cainlevy; will review this weekend. 

@ejcx: any qualms?

**Comment by cainlevy** [comment]
Anything I can do to move this forward?

**Comment by ejcx** [comment]
Whoops. looks like I was the blocker here. Looks like this makes ACAO * always turned on, which is safe? I don't really know why you would want that but I don't see any issues with it.

**Comment by cainlevy** [comment]
My intent here is that ACAO * is returned when:

* CORS is running with all defaults (no custom validator, no specified origins)
* CORS has been configured with an explicit `*`

Otherwise, the current origin is reflected on the assumption that it has been previously validated by either a custom validator or a matching origin.

**Comment by ejcx** [comment]
SGTM!

**Comment by kisielk** [comment]
@elithrar what's the word on this one?

**Comment by elithrar** [comment]
Sorry for the long delay here! Merged.

**Pull request merged**
