### PR TITLE
Added the CORS handler -- continued

### PR DESCRIPTION
**Pull request by vincent-petithory**
This is hopefully the completion of PR #8 based on the feedback it got.

### CODE REVIEW

**Comment by elithrar** [comment]
Just going to bump this with some commentary—as a contributor but not the maintainer—but overall this looks really solid.

It'd be nice if it usage was more similar to existing middleware handlers in this package:

* Provide a middleware function that you can configure and then wrap your router (or individual handler functions) with—e.g.

```go
type cors struct {
    h http.Handler
    opts *CORSOptions
}

type CORSOptions {
    // Same fields as the current CORSHandler
}

func CORSHandler(opts *CORSOptions) func(http.Handler) http.Handler {
     return func(h http.Handler) http.Handler {
         return cors{h, opts}
    }
}

* Make the changes in `func (h CORSHandler) ServeHTTP(w http.ResponseWriter, req *http.Request)` to instead reference `h.opts` (where needed) and to call `h.h.ServeHTTP(w, r)` if the checks pass.

If there's not a desire to change it, or if there is but time is a problem, let me know and I may be able to find the time to refactor.

**Comment by vincent-petithory** [comment]
@elithrar The changes make sense and I'm fine with them.
Now the pull request suffers a lack of interest so I'm not sure this is worth the time for now.

**Comment by elithrar** [comment]
I'm keen to get a version of this merged in—@kisielk, can you mark as HelpWanted? The core of the PR is really good and if someone can find time more easily than I can it'd be great to get this merged.

Needs:

* Refactor to accept options or potentially [the functional options approach] in https://github.com/gorilla/csrf/blob/master/csrf.go#L120
* Good tests
* A godoc example above the public handler function

**Comment by kisielk** [comment]
Added the label. Also added the org owners as collaborators, not sure why they weren't there before.

**Comment by njohns-grovo** [comment]
i have some extra time this month to work on this, would it be appropriate to open a new PR if @vincent-petithory does not have time to continue?

**Comment by elithrar** [comment]
That would be great. New PR preferred.

**Comment by elithrar** [comment]
@njohns-grovo Are you still interested in contributing this? If you are, but haven't started yet, I can push a skeleton branch tonight for you to pick up and run with.

**Comment by njohns-grovo** [comment]
@elithrar yes, sorry it's been quite busy at work recently if you push up a branch i'll knock it out this week!

**Comment by elithrar** [comment]
No worries. I've been busy as well—I've just about got a skeleton with the
basics down. I'll push that up late today and add a checklist to track
progress.

**Comment by elithrar** [comment]
See #56!

**Pull request closed without merging**
