### PR TITLE
[cors]: allow users to disable preflight caching

### LINKED ISSUE #246: [FEATURE] Allow users to disable caching of preflight responses
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Is your feature request related to a problem? Please describe.

Omitting the `Access-Control-Max-Age` header from a preflight response leads browsers to cache that response for [5 seconds](https://fetch.spec.whatwg.org/#http-access-control-max-age), whereas including

```http
Access-Control-Max-Age: 0
```

in a preflight instructs browsers not to cache that preflight response. However, the CORS middleware ignores that distinction and takes a `maxAge` value of `0` [as a cue to omit the `Access-Control-Max-Age` header](https://github.com/gorilla/handlers/blob/fc9305756b095d6a0aede51f06fc85933647a25f/cors.go#L97). Therefore, it prevents its users from disabling caching of preflight responses.

### Describe the solution that you would like.

Fortunately, since the CORS middleware uses the functional-options pattern (as opposed to exposing a config struct to users), retrofitting it to understand this distinction (0 value set/unset) should be straightforward. Maintainers could add `customMaxAge bool` field to the `cors` struct type and set it when the `MaxAge` option is called.

### Describe alternatives you have considered.

Alternatively, maintainers could change the type of `cors.maxAge` from `int` to `*int`, where a `nil` value indicates that users haven't set a max age.

### Anything else?

- [jub0bs - Fearless CORS: a design philosophy for CORS middleware libraries (and a Go implementation)](https://jub0bs.com/posts/2023-02-08-fearless-cors/#impossibility-to-turn-preflight-caching-off)
- [Julien Cretel - Useful Functional-Options Tricks for Better Libraries (GopherCon Europe 2023)](https://www.youtube.com/watch?v=5uM6z7RnReE&t=5m57s)
- https://github.com/rs/cors/issues/152
- https://github.com/labstack/echo/issues/2471
- https://github.com/gofiber/fiber/issues/2609

### PR DESCRIPTION
**Pull request by jub0bs**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Related Tickets & Documents

- Related Issue #246 
- Closes #246 

## Added/updated tests?

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Run verifications and test

- [ ] `make verify` is passing
- [x] `make test` is passing

### CODE REVIEW

**Comment by jub0bs** [comment]
No feedback from maintainers in more than three months... Is this project still maintained?

**Comment by AlexVulaj** [comment]
@jub0bs Hey there - we're a small team coming out of a large transitional process and doing our best to keep on top of things, mainly prioritizing bugs and other issues over new features still. We appreciate your patience as we work through our large backlog, and thanks for contributing!

**Comment by jub0bs** [comment]
No reactivity from maintainers. Closing this PR.

**Comment by jaitaiwan** [comment]
I took a brief look, I think the bool is unnecessary. I need to look at if the maxAge has a default value when unset but it appears to me we’d just change the condition to > -1.

**Comment by jub0bs** [comment]
@jaitaiwan See https://github.com/gorilla/handlers/pull/250, which also aims to fix https://github.com/gorilla/handlers/issues/246 but in a slightly different way.

Additional resources on the topic:
- https://jub0bs.com/posts/2023-02-08-fearless-cors/#impossibility-to-turn-preflight-caching-off
- https://pkg.go.dev/github.com/jub0bs/cors#hdr-MaxAgeInSeconds

**Pull request closed without merging**
